#===------------------------------------------------------------------------===#
#
# This source file is part of the DeviceKit project
#
# Copyright © 2015 - 2016 Dennis Weissmann and all project contributors
#
#===------------------------------------------------------------------------===#

excluded: # paths to ignore during linting. overridden by `included`.

disabled_rules: 
  - line_length
  - force_try
  - type_name
  - cyclomatic_complexity
  - todo
  - file_length

type_body_length:
  - 300 # warning
  - 400 # error

variable_name_max_length:
  - 40 # warning
  - 60 # error

variable_name_min_length:
  - 3 # warning
  - 1 # error
